config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions'
  }
  # deviseコントローラーのカスタマイズ(sign_up,sign_in時のpoint作成のため)
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions      => 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # ルート設定
  root 'users#index'
  # aboutページ設定
  get 'home/about', to: 'home#about'
  # namespaceを使い指定のパス(admin)にする
  namespace :admins do
    resources :users,        except: [:new, :create]
    resources :diaries,      only: [:index, :show, :destroy]
    resources :meal_records, only: [:show]
    resources :genres,       only: [:index, :create, :edit, :update]
    resources :topics
  end
  # ルーティングをネストする
  resources :users, except: [:new, :create] do
    resource :relationships, only: [:create, :destroy]
    # 自user以外のidが必要なためresourcesによって作成
    resources :relationships, only: [:index]
  end
  get       'congfirm' => 'users#congfirm'

  # ルーティングをネストする
  resources :diaries do
    resources :diary_comments, except: [:new, :index]
  end

  resources :meal_records, except: [:index]
  resources :topics,         only: [:index, :show]

end

app/models/diary_comment.rb
class DiaryComment < ApplicationRecord
  # アソシエーション設定
  belongs_to :user
  belongs_to :diary

  # バリデーション設定
  validates :content, presence: true

end

app/controllers/diary_comments_controller.rb
class DiaryCommentsController < ApplicationController
  # ログイン済みユーザーにのみアクセスを許可する(deviseのメソッド)
  before_action :authenticate_user!

  def create
    user = current_user
    @diary = Diary.find(params[:diary_id])
    @comment = @diary.diary_comments.build(diary_comment_params)
    @comment.user_id = user.id
    if @comment.save
      render :index
    else #if文でエラー時の分岐表示
      redirect_to diary_path(@diary), notice: 'コメントを入力してください'
    end
  end

  def destroy
    user = current_user
    @diary = Diary.find(params[:diary_id])
    @comment = DiaryComment.find(params[:id])
    @comment.destroy
    render :index
  end

  private
  def diary_comment_params
    params.require(:diary_comment).permit(:content)
  end

end

app/helpers/diary_comments_helper.rb
module DiaryCommentsHelper
end

app/views/diary_comments/_form.html.erb
<!-- form_withではデフォルトでremote: true(JS形式) -->
<%= form_with model: [diary, comment] do |f| %>
  <%= f.text_area :content, class: "form-control", rows: 5, placeholder: "コメントはここに" %>
  <%= f.submit "コメントする", class: "btn btn-warning" %>
<% end %>

app/views/diary_comments/_index.html.erb
<tbody>
  <% comments.each do |comment| %>
  <tr>
    <td>
      <%= link_to user_path(comment.user) do %>
      <%= attachment_image_tag comment.user, :profile_image, size: '50x50', format: 'jpeg' %>
      <% end %>
    </td>
    <td><%= comment.content %></td>
    <% if user_signed_in? %>
      <% if comment.user == current_user %>
        <td>
          <!-- ルーティングをネストしているため引数が２つ(diary.id,comment.id)必要 -->
          <!-- remote: trueにてJS形式でリクエストを送る -->
          <%= link_to "削除", diary_diary_comment_path(comment.diary, comment), method: :delete, class: "btn-sm btn-danger btn-sm", remote: true %>
        </td>
      <% end %>
    <% end %>
  </tr>
  <% end %>
</tbody>

app/views/diary_comments/index.js.erb
$("#comments_area").html("<%= j(render partial: 'index', locals: { comments: @comment.diary.diary_comments }) %>")
$("textarea").val('')