config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions'
  }
  # deviseコントローラーのカスタマイズ(sign_up,sign_in時のpoint作成のため)
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions      => 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # ルート設定
  root 'users#index'
  # aboutページ設定
  get 'home/about', to: 'home#about'
  # namespaceを使い指定のパス(admin)にする
  namespace :admins do
    resources :users,        except: [:new, :create]
    resources :diaries,      only: [:index, :show, :destroy]
    resources :meal_records, only: [:show]
    resources :genres,       only: [:index, :create, :edit, :update]
    resources :topics
  end
  # ルーティングをネストする
  resources :users, except: [:new, :create] do
    resource :relationships, only: [:create, :destroy]
    # 自user以外のidが必要なためresourcesによって作成
    resources :relationships, only: [:index]
  end
  get       'congfirm' => 'users#congfirm'

  # ルーティングをネストする
  resources :diaries do
    resources :diary_comments, except: [:new, :index]
  end

  resources :meal_records, except: [:index]
  resources :topics,         only: [:index, :show]

end

app/models/diary.rb
class Diary < ApplicationRecord
  # アソシエーション設定
  belongs_to :user
  has_one    :body_weight,    dependent: :destroy
  has_many   :meal_records,   dependent: :destroy
  has_many   :diary_comments, dependent: :destroy

  # バリデーション設定
  # :onオプションでupdate時のみバリデーションを設定
  validates :activity_status, presence: true, on: :update
  # uniquenessで一意であることを定義scopeにて範囲を指定
  validates :created_on,      presence: true, uniqueness: { scope: :user_id }


  # enum機能の定義
  enum activity_status: { 低い: 0, 普通: 1, 高い: 2 }

  # タグ機能
  # acts_as_taggable_on :tagsと同じ意味（エイリアス）
  acts_as_taggable

  end

app/controllers/admins/diaries_controller.rb
class Admins::DiariesController < ApplicationController
  # adminログイン時にのみアクセスを許可する(deviseのメッソド)
  before_action :authenticate_admin!

  def index
    @diaries = Diary.page(params[:page]).reverse_order.per(12)
  end

  def show
    @diary = Diary.find(params[:id])
    # @diaryに紐づいたmeal_recordsを取得
    @meal_records = @diary.meal_records
    @comments = @diary.diary_comments
  end

  def destroy
    @diary = Diary.find(params[:id])
    @diary.destroy
    redirect_to admins_diaries_path
  end

end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  # ログイン済みユーザーにのみアクセスを許可する(deviseのメソッド)
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update]

  def new
    # viewへ渡すためのインスタンス変数に空のモデルオブジェクトを作成
    @diary = Diary.new
    @body_weight = BodyWeight.new
  end

  def create
    user = current_user
    # build=モデルオブジェクトを生成(newの別名)
    # 1対Nの際、buildによる関連付けメソッド(関連付けメソッド名.build)を使用
    @diary = user.diaries.build(diary_params)
    # 1対１の際、buildによる関連付けメソッド(build_関連付けメソッド名)を使用
    @body_weight = @diary.build_body_weight(
      user_id:       user.id,
      weight_record: params[:diary][:body_weight][:weight_record]
      )
    if @diary.save
      # 日記作成ポイント付与
      Reward.give_point(user,2)
      # body_weight作成
      if @body_weight.save
        # 目標体重達成ポイント付与
        if @body_weight.weight_record <= user.goal_weight
          Reward.give_point(user,4)
        end
        # ランクステータ変更確認(ポイント取得後)
        user.change_rank(user.rewards.total_point)
        # createで新規食事記録画面へ遷移（パラメーターをredirect_toに直接渡す）
        redirect_to new_meal_record_path(id: @diary.id), notice: '日記作成ポイント(10point)獲得しました！<br>引き続き食事記録を追加してください'
      else #if文でエラー時の分岐表示
        @meal_records = @diary.meal_records
        flash.now[:alert] = '体重を入力してください'
        render :edit
      end
    else #if文でエラー時の分岐表示
      render :new
    end
  end

  def index
    # 遷移元のリンクにより表示を分岐する
    if params[:index] == "user"
      @user = User.find(params[:id])
      @diaries = @user.diaries.page(params[:page]).reverse_order
    else
      @diaries = Diary.page(params[:page]).reverse_order
    end
    # タグ検索
    if params[:tag_name]
      @diaries = Diary.tagged_with("#{params[:tag_name]}").page(params[:page]).reverse_order
    end
  end

  def show
    @diary = Diary.find(params[:id])
    # @diaryに紐づいたmeal_recordsを取得
    @meal_records = @diary.meal_records.order(intake_status: :asc)
    # comment表示、作成
    @comments = @diary.diary_comments
    @comment = DiaryComment.new
  end

  def edit
    @diary = Diary.find(params[:id])
    @meal_records = @diary.meal_records.order(intake_status: :asc)
    # find_byメソッドによりdairy_idより取得
    unless @body_weight = BodyWeight.find_by(diary_id: params[:id])
      @body_weight = BodyWeight.new
    end
  end

  def update
    @diary = Diary.find(params[:id])
    @meal_records = @diary.meal_records
    unless @body_weight = BodyWeight.find_by(diary_id: params[:id])
      @body_weight = @diary.build_body_weight(
      user_id:       current_user.id,
      weight_record: params[:diary][:body_weight][:weight_record]
      )
    end
    if @diary.update(diary_params)
      if @body_weight.update(
        weight_record: params[:diary][:body_weight][:weight_record]
        )
        redirect_to diary_path(@diary.id), notice: '更新が成功しました！'
      elsif @body_weight.save
        redirect_to diary_path(@diary.id), notice: '更新が成功しました！'
      else
        flash.now[:alert] = '体重を入力してください'
        render :edit
      end
    else #if文でエラー時の分岐表示
      render :edit
    end
  end

  def destroy
    @diary = Diary.find(params[:id])
    @diary.destroy
    redirect_to diaries_path
  end

  private
  def diary_params
    params.require(:diary).permit(:remark, :activity_status, :tag_list, :created_on)
  end
  # url直打ち防止
  def correct_user
    diary = Diary.find(params[:id])
    if current_user.id != diary.user.id
      redirect_to diary_path
    end
  end

end

app/helpers/admins/diaries_helper.rb
module Admins::DiariesHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/views/diaries/_tag_list.html.erb
<% tag_list.each do |tag| %>
  <span class="label label-success"><%= link_to tag, diaries_path(tag_name: tag) %></span>
<% end %>

app/views/diaries/edit.html.erb
<div class="main container">
  <div class="form edit">
    <div class="row">
      <div class="col-xs-12 center">
        <%= form_with model: @diary, local: true do |f| %>
        <!-- エラーメッセージの部分テンプレート(f.objectで@diaryをmodelに渡す) -->
        <%= render 'layouts/error_messages', model: f.object %>
        <h1 class="diary">日記編集画面</h1>
        <div class="row">

          <div class="col-xs-5 col-xs-offset-1 title diary-show">
            <h3>食事記録</h3>
            <table class="table">
              <thead>
                <tr>
                  <th>タイミング</th>
                  <th>イメージ</th>
                  <th>タイトル</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% @meal_records.each do |meal| %>
                <tr>
                  <td class="meal-text"><%= meal.intake_status %></td>
                  <td class="meal-text"><%= attachment_image_tag meal, :meal_image, size: "70x70", class: "img-rounded meal-image", fallback: "no_image1.jpg" %></td>
                  <td class="meal-text topic-titile"><%= meal.title %></td>
                  <td class="meal-text"><%= link_to "編集", edit_meal_record_path(meal), class: "btn btn-success" %></td>
                </tr>
                <% end %>
              </tbody>
            </table>
            <%= link_to "追加する", new_meal_record_path(id: @diary.id), class: "btn btn-warning" %>
          </div>

          <div class="col-xs-5 col-xs-offset-1 edit_diary">

            <%= f.fields_for @body_weight do |weight| %>
            <div class="form-group row">
              <div class="col-xs-4 diary-form-1">
                <%= weight.label :体重 %><br>
                <%= weight.number_field :weight_record, min: 0, autocomplete: "weight_record", class: "form-control" %>
              </div>
            </div>
            <% end %>
            <div class="form-group row">
              <div class="col-xs-4 diary-form-1">
                <%= f.label :活動量 %><br>
                <%= f.select :activity_status, Diary.activity_statuses.keys.to_a, prompt: "選択してください", autocomplete: "activity_status", class: "form-control" %>
              </div>
            </div>
            <div class="form-group row">
              <div class="col-xs-7 diary-form-2">
                <%= f.label :メモ %><br>
                <%= f.text_area :remark, autocomplete: "remark", class: "form-control" %>
              </div>
            </div>
            <div class="form-group row">
              <div class="col-xs-7 diary-form-2">
                <%= f.label :タグ %><br>
                <%= f.text_field :tag_list, value: @diary.tag_list.join(','), class: "form-control" %>
              </div>
            </div>
          </div>
        </div>
        <div class="back">
          <%= f.submit "更新する", class: "btn btn-success" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/diaries/index.html.erb
<div class="main container">
  <div class="icon">
    <%= link_to new_diary_path do %>
      <i class="fas fa-plus-circle fa-4x"></i>
    <% end %>
  </div>
  <div class="row">
    <% @diaries.each do |diary| %>
    <div class="col-xs-3 index">
      <div class="diary-index center">
        <%= attachment_image_tag diary.user, :profile_image, size: "100x100", class: "img-circle", fallback: "no_image.jpg" %><br>
        <%= diary.user.name %>
        <p><%= link_to diary.created_on.strftime('%Y年%m月%d日'), diary_path(diary) %>の日記</p>
        <%= render "diaries/tag_list", tag_list: diary.tag_list %>
      </div>
    </div>
    <% end %>
  </div>
  <div class="center">
    <%= paginate @diaries, class: "paginate" %>
  </div>
</div>

app/views/diaries/new.html.erb
<div class="main container">
  <div class="form edit">
    <div class="row">
      <div class="col-xs-12 center">
        <h1>日記作成画面</h1>
        <%= form_with model: @diary, local: true do |f| %>
        <!-- エラーメッセージの部分テンプレート(f.objectで@diaryをmodelに渡す) -->
        <%= render 'layouts/error_messages', model: f.object %>

        <div class="form-group row">
          <div class="col-xs-2 col-xs-offset-5 diary-form1">
            <%= f.label :日付 %><br>
            <%= f.date_field :created_on, class: "form-control" %>
          </div>
        </div>

        <%= f.fields_for @body_weight do |f| %>
        <div class="form-group row">
          <div class="col-xs-2 col-xs-offset-5 diary-form1">
            <%= f.label :体重 %><br>
            <%= f.number_field :weight_record, min: 0, class: "form-control" %>
            <% end %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-xs-4 col-xs-offset-4 diary-form2">
            <%= f.label :メモ %><br>
            <%= f.text_area :remark, class: "form-control" %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-xs-4 col-xs-offset-4 diary-form1">
            <%= f.label :活動量 %><br>
            <%= f.select :activity_status, Diary.activity_statuses.keys.to_a, prompt: "選択してください", class: "form-control" %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-xs-4 col-xs-offset-4 diary-form2">
            <%= f.label :タグ %><br>
            <%= f.text_field :tag_list, value: @diary.tag_list.join(','), class: "form-control", placeholder: "複数入力の場合カンマ(,)区切り" %>
          </div>
        </div>
        <div class="action">
          <%= f.submit "食事記録を追加する", class: "btn btn-success" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/diaries/show.html.erb
<div class="main container">
  <div class="form edit">
    <div class="row">
      <div class="col-xs-12 center">
        <h1 class="diary"><%= @diary.created_on.strftime('%Y年%m月%d日') %></h1>
        <div class="row">
          <div class="col-xs-5 col-xs-offset-1 title diary-show">
            <h3>食事記録</h3>
            <table class="table">
              <thead>
                <tr>
                  <th>タイミング</th>
                  <th>イメージ</th>
                  <th>タイトル</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% @meal_records.each do |meal| %>
                <tr>
                  <td class="meal-text"><%= meal.intake_status %></td>
                  <td class="meal-text"><%= attachment_image_tag meal, :meal_image, size: "70x70", class: "img-rounded meal-image", fallback: "no_image1.jpg" %></td>
                  <td class="meal-text topic-titile"><%= meal.title %></td>
                  <td class="meal-text"><%= link_to "詳細", meal_record_path(meal), class: "btn btn-success" %></td>
                </tr>
                <% end %>
              </tbody>
            </table>

          </div>
          <div class="col-xs-5 col-xs-offset-1 edit_diary text-left">
            <h3>メモ</h3>
              <p><%= simple_format(@diary.remark) %></p>
            <h3>活動量</h3>
              <p><%= @diary.activity_status %></p>
            <h3>タグ</h3>
              <h4><%= render "diaries/tag_list", tag_list: @diary.tag_list %></h4>
            <% if user_signed_in? %>
              <% if @diary.user.id == current_user.id %>
                <div class="action">
                  <%= link_to "編集", edit_diary_path(@diary.id), class: "btn btn-success" %>
                  <%= link_to "削除", diary_path(@diary), method: :delete, class: "btn btn-danger" %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-6 col-xs-offset-3 title comment">
            <h3>コメント</h3>
            <table id= "comments_area" class="table">
              <!-- 投稿されたコメント一覧を表示するためのrender(部分テンプレート) -->
              <%= render partial: 'diary_comments/index', locals: { comments: @comments } %>
            </table>
            <% if user_signed_in? %>
              <!-- コメント入力欄を表示するためのrender(部分テンプレート) -->
              <%= render partial: 'diary_comments/form', locals: { diary: @diary, comment: @comment } %>
            <% end %>
          </div>
        </div>
        <div class="action">
          <%= link_to "戻る", 'javascript:history.back()', class: "btn btn-info btn-sm" %>
        </div>
      </div>
    </div>
  </div>
</div>