config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions'
  }
  # deviseコントローラーのカスタマイズ(sign_up,sign_in時のpoint作成のため)
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions      => 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # ルート設定
  root 'users#index'
  # aboutページ設定
  get 'home/about', to: 'home#about'
  # namespaceを使い指定のパス(admin)にする
  namespace :admins do
    resources :users,        except: [:new, :create]
    resources :diaries,      only: [:index, :show, :destroy]
    resources :meal_records, only: [:show]
    resources :genres,       only: [:index, :create, :edit, :update]
    resources :topics
  end
  # ルーティングをネストする
  resources :users, except: [:new, :create] do
    resource :relationships, only: [:create, :destroy]
    # 自user以外のidが必要なためresourcesによって作成
    resources :relationships, only: [:index]
  end
  get       'congfirm' => 'users#congfirm'

  # ルーティングをネストする
  resources :diaries do
    resources :diary_comments, except: [:new, :index]
  end

  resources :meal_records, except: [:index]
  resources :topics,         only: [:index, :show]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # attachmentメソッド（gem:refile)使用
  attachment :profile_image

  # アソシエーション設定
  has_many :diaries,        dependent: :destroy
  has_many :body_weights,   dependent: :destroy
  has_many :rewards,        dependent: :destroy
  has_many :diary_comments, dependent: :destroy

  # バリデーション設定
  validates :name,        presence: true, length: { maximum: 15 }
  validates :gender,      presence: true
  validates :birthday,    presence: true
  validates :goal_weight, numericality: { only_integer: true }
  # 空欄を許可
  validates :height,          numericality: { only_integer: true }, allow_blank: true
  validates :total_point,     numericality: { only_integer: true }
  validates :introduction,    length: { maximum: 50 }
  validates :mail_permission, inclusion: { in: [true, false] }


  # enum機能の定義
  enum gender:        { 男性: 0, 女性: 1, その他: 2 }
  enum public_status: { 公開: 0, 非公開: 1 }
  enum rank_status:   { グリーン: 0, シルバー: 1, ゴールド: 2 }

  # 現在の体重取得
  def latest_diary
    diaries.order(created_on: :desc).first
  end
  # ぼっち演算子でnilガード
  def latest_weight_record
    latest_diary&.body_weight&.weight_record
  end

  # ランクステータス変更メソッド
  def change_rank(point)
    # ゴールドランク変更(200point以上)
    if point >= 200
      update(rank_status: 2)
    # シルバーランク変更(100point以上)
    elsif point >= 100
      update(rank_status: 1)
    else
    # グリーンランク(初期ランク)
      update(rank_status: 0)
    end
  end

  #自分がフォローしている人
  # フォローする側のUser(="follower_id")からみてフォローされるUserを中間テーブル(follower)を介して集める
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  # 中間テーブル(follower)を通して(through)、followedモデル(source)のUser(フォローされた側)を集めることをfollowing_userと定義する
  has_many :following_user, through: :follower, source: :followed

  #自分をフォローしている人
  # フォローされる側のUser(="followed_id")からみてフォローしてくるUserを中間テーブル(followed)を介して集める
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  # 中間テーブル(followed)を通して(through)、followerモデル(source)のUser(フォローする側)を集めることをfollower_userと定義する
  has_many :follower_user,  through: :followed, source: :follower

  # フォローする・フォロー外す・フォローしているか確認を行うメソッドの定義
  # フォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end
  # フォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end
  # フォローしているか確認(フォローしてればtrueを返す)
  def following?(user)
  following_user.include?(user)
  end

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  # adminログイン時にのみアクセスを許可する(deviseのメッソド)
  before_action :authenticate_admin!

  def index
    @users = User.page(params[:page]).reverse_order.per(12)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admins_user_path(@user), notice: '更新が成功しました'
    else #if文でエラー時の分岐表示
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admins_users_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :gender, :birthday, :height, :goal_weight, :public_status, :email, :introduction, :profile_image, :mail_permission)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
   def create
     super
       if user_signed_in?
         # sign_up時のポイント機能
         Reward.give_point(current_user,0)
        end
        flash[:notice] = '新規登録が完了しました！<br>新規登録ポイント(50point)取得しました！'
   end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
   def create
     super
     user = current_user
     # sign_in時のポイント機能(１日1回付与)(UTC時刻を基準にしているため時差分-9時間調整)
     time0 = Time.current.midnight.advance(hours: -9)
     time1 = Time.current.end_of_day.advance(hours: -9)
     # 同じハッシュ内に複数並べ条件を追加
     unless user.rewards.where(issue_reason: 1, created_at: time0..time1).exists?
     Reward.give_point(user,1)
      # ランクステータ変更確認(ポイント取得後)
      user.change_rank(user.rewards.total_point)
     end
   end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # ログイン済みユーザーにのみアクセスを許可する(deviseのメソッド)
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user,       only: [:edit, :update]
  before_action :forbid_test_user,   only: [:update, :destroy]

  def index
    # ソート機能分岐
    if params[:sort] == "point"
      @users = User.order(total_point: "DESC").page(params[:page])
    elsif params[:sort] == "diary"
      @users = User.joins("left join diaries on diaries.user_id = users.id").group(:id).order(Arel.sql("count(*) desc")).page(params[:page])
    elsif params[:sort] == "follower"
      @users = User.joins("left join relationships on followed_id = users.id").group(:id).order(Arel.sql("count(followed_id) desc")).page(params[:page])
    else
      @users = User.page(params[:page]).reverse_order
    end
  end

  def show
    @user = User.find(params[:id])
    # グラフ用体重データ取得(pluckによりカラムの配列を取得)(to_hメソッドにより配列をハッシュに変換)
    @user_data = @user.diaries.joins(:body_weight).order('diaries.created_on').pluck('diaries.created_on', 'body_weights.weight_record').to_h
    if user_signed_in?
      @self_data = current_user.diaries.joins(:body_weight).order('diaries.created_on').pluck('diaries.created_on', 'body_weights.weight_record').to_h
    end
  end

  def edit
    @user =User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: '更新が成功しました！'
    else #if文でエラー時の分岐表示
      render :edit
    end
  end

  def congfirm
    @user = current_user
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path, notice: '退会が完了しました'
  end

  private

  def user_params
    params.require(:user).permit(:name, :gender, :birthday, :height, :goal_weight, :public_status, :email, :introduction, :profile_image, :mail_permission)
  end
  # url直打ち防止
  def correct_user
    user = User.find(params[:id])
    if current_user != user
      redirect_to user_path
    end
  end
  # テストユーザー用フィルター
  def forbid_test_user
    user = User.find(params[:id])
    if user.email == "test@test"
      flash[:notice] = "テストユーザーのため変更,退会はできません"
      redirect_to root_path
    end
  end

end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<div class="row">
  <% users.each do |user| %>
  <div class="col-xs-3 index">
    <div class="user-index center">
      <%= link_to user_path(user) do %>
        <%= attachment_image_tag user, :profile_image, size: "100x100", class: "img-circle", fallback: "no_image.jpg" %><br>
        <%= user.name %>
      <% end %>
      <p>フォロー：<%= link_to user.follower.count, user_relationships_path(user_id: user.id, index: "follower") %></p>
      <p>フォロワー：<%= link_to user.followed.count, user_relationships_path(user_id: user.id, index: "followed") %></p>
      <p><%= user.rank_status %>（<%= user.rewards.total_point %>point）</p>
      <% if user.public_status == "公開" %>
        <p>身長<%= user.height %>cm 体重<%= user.latest_weight_record %>kg</p>
        <p>目標体重<%= user.goal_weight %>kg</p>
      <% else %>
        <p>身長：非公開</p>
        <p>体重：非公開</p>
      <% end %>
      <p>日記投稿数：<%= link_to user.diaries.count, diaries_path(index: "user", id: user.id) %>件</p>
      <% if user_signed_in? && current_user != user %>
        <% if current_user.following?(user) %>
          <%= link_to "フォローを外す", user_relationships_path(user.id), { method: :delete, class: "btn  btn-danger" } %>
        <% else %>
          <%= link_to "フォローする", user_relationships_path(user.id), { method: :POST, class: "btn  btn-success" } %>
        <% end %>
      <% end %>
    </div>
  </div>
  <% end %>
</div>
<div class="center">
  <%= paginate users, class: "paginate" %>
</div>

app/views/users/congfirm.html.erb
<div class="main container">
  <div class="row">
    <div class="congfirm center">
      <h3>本当に退会しますか？</h3>
      <p>退会すると、取得ポイントや<br>
        これまでの投稿が削除されます。<br>
        退会する場合は、「退会する」をクリックしてください。</p>
      <%=link_to "退会しない", user_path(@user), class: "btn btn-success" %>
      <%=link_to "退会する", user_path(@user),method: :delete, class: "btn btn-danger" %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="main container">
  <div class="form edit">
    <div class="row">
      <div class="col-xs-12 center">
        <h1>会員情報編集画面</h1>
        <%= form_with model: @user, local: true do |f| %>
        <!-- エラーメッセージの部分テンプレート(f.objectで@userをmodelに渡す) -->
        <%= render 'layouts/error_messages', model: f.object %>

        <div class="form-group row">
          <div class="col-xs-4 col-xs-offset-4 user-edit">
            <%= attachment_image_tag @user, :profile_image, size: "100x100", class: "img-circle", fallback: "no_image.jpg" %>
            <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-xs-4 col-xs-offset-4 user-edit">
            <%= f.label :ユーザー名 %><br>
            <%= f.text_field :name, autofocus:true, autocomplete: "name", class: "form-control" %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-xs-2 col-xs-offset-5 user-edit">
            <%= f.label :性別 %><br>
            <%= f.select :gender, User.genders.keys.to_a, prompt: "選択してください" %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-xs-2 col-xs-offset-5 user-edit">
            <%= f.label :生年月日 %><br>
            <!-- use_month_numbers（月の表示を数字で表示） -->
            <%= f.date_select :birthday, start_year: 1930, end_year: Time.current.year, prompt: "--", use_month_numbers: true %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-xs-2 col-xs-offset-5 user-edit">
            <%= f.label :身長 %><br>
            <%= f.number_field :height, min: 0, class: "form-control", id: "height" %>
          </div>
        </div>

        <div class="form-group row" id="text">
          <div class="col-xs-2 col-xs-offset-5 user-edit">
            <%= f.label :目標体重 %><br>
            <%= f.number_field :goal_weight, min: 0, class: "form-control" %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-xs-2 col-xs-offset-5 user-edit">
            <%= f.label :公開ステータス %><br>
            <%= f.label :公開ステータス, :公開 %>
            <%= f.radio_button :public_status, "公開", checked: true %>
            <%= f.label :公開ステータス, :非公開 %>
            <%= f.radio_button :public_status, "非公開" %>
          </div>
        </div>
        
        <div class="form-group row">
          <div class="col-xs-4 col-xs-offset-4 user-edit">
            <%= f.label :メールアドレス %><br />
            <%= f.email_field :email, autocomplete: "email", class: "form-control" %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-xs-4 col-xs-offset-4 user-edit">
            <%= f.label :トピックス配信設定 %><br>
            <%= f.label :トピックス配信設定, :メールを受け取る %>
            <%= f.radio_button :mail_permission, "true" %>
            <%= f.label :トピックス配信設定, :メールを受け取らない %>
            <%= f.radio_button :mail_permission, "false" %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-xs-4 col-xs-offset-4 user-edit">
            <%= f.label :自己紹介 %><br />
            <%= f.text_area :introduction, autocomplete: "introduction", class: "form-control" %>
          </div>
        </div>

        <div>
          <%= f.submit "保存する", class: "btn btn-success" %>
          <%= link_to "戻る", 'javascript:history.back()', class: "btn btn-info" %>
        </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="main container">
  <div class="icon">
	    <div class="col-xs-3">
        <%= select_tag("sort", options_for_select({登録日時の新しい順: "new", ポイント数の多い順: "point", 日記投稿数の多い順: "diary", フォロワーの多い順:   "follower"}), include_blank: "並び替え", class: "form-control")%>
      </div>
    <%= link_to new_diary_path do %>
      <i class="fas fa-plus-circle fa-4x"></i>
    <% end %>
  </div>
  <%= render 'users/index', users: @users %>
</div>

app/views/users/show.html.erb
<div class="main container">
  <div class="profile">
    <div class="row">
      <div class="col-xs-4 col-xs-offset-1 right">
        <%= attachment_image_tag @user, :profile_image, size: "100x100", class: "img-circle show-image", fallback: "no_image.jpg" %>
      </div>
      <div class="col-xs-7">
        <h3 class="name"><%= @user.name %></h3>
          <h4 class="name">
            <% if @user.rank_status == "グリーン" %>
              <i class="fas fa-medal green"></i>
            <% elsif @user.rank_status == "シルバー" %>
              <i class="fas fa-medal silver"></i>
            <% else %>
              <i class="fas fa-medal gold"></i>
            <% end %>
            <%= @user.rank_status %>ランク（<%= @user.rewards.total_point %>point）
          </h4>
      </div>
    </div>
    <!-- 情報公開設定 -->
    <% if @user.public_status == "公開" %>
      <div class="row">
        <div class="col-xs-12">
          <!-- チャート表示 -->
          <% if user_signed_in? %>
            <%= line_chart [
              {name: @user.name, data: @user_data},
              {name: "自分", data: @self_data},
              ], discrete: true %>
          <% else %>
            <%= line_chart @user_data, discrete: true %>
          <% end %>
        </div>
      </div>
    <!-- 非公開 -->
    <% else %>
      <div class="row">
        <div class="col-xs-12 box">
          <div class="box-text">非公開</div>
        </div>
      </div>
    <% end %>
    <!-- 情報公開設定 -->
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2 user-show">
        <h3>詳細情報</h3>
        <table class="table user-show">
          <tbody>
            <tr>
              <th class="user-th">ユーザー名</th>
              <td><%= @user.name %>（日記投稿数：<%= link_to @user.diaries.count, diaries_path(index: "user", id: @user.id) %>件）</td>
            </tr>
            <tr>
              <th>ランク</th>
              <td><%= @user.rank_status %>ランク（<%= @user.rewards.total_point %>point）</td>
            </tr>
            <!-- 情報公開設定 -->
            <% if @user.public_status == "公開" %>
              <tr>
                <th>性別</th>
                <td><%= @user.gender %></td>
              </tr>
              <tr>
                <th>生年月日</th>
                <td><%= @user.birthday.strftime('%Y年%m月%d日') %></td>
              </tr>
              <tr>
                <th>身長</th>
                <td><%= @user.height %>cm</td>
              </tr>
              <tr>
                <th>目標体重</th>
                <td><%= @user.goal_weight %>kg</td>
              </tr>
            <!-- 非公開 -->
            <% else %>
              <tr>
                <th>性別</th>
                <td>非公開</td>
              </tr>
              <tr>
                <th>生年月日</th>
                <td>非公開</td>
              </tr>
              <tr>
                <th>身長</th>
                <td>非公開</td>
              </tr>
               <tr>
                <th>目標体重</th>
                <td>非公開</td>
              </tr>
            <% end %>
            <!-- 情報公開設定 -->
            <tr>
              <th>自己紹介</th>
              <td><%= simple_format(@user.introduction) %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <% if user_signed_in? %>
      <% if @user.id == current_user.id %>
        <div class="center">
          <%= link_to "編集する", edit_user_path(@user), class: "btn btn-success" %>
          <%= link_to "退会する", congfirm_path, class: "btn btn-danger" %>
        </div>
      <% end %>
    <% end %>
    <div class="back center">
      <%= link_to "戻る", 'javascript:history.back()', class: "btn btn-info btn-sm" %>
    </div>
  </div>
</div>